import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import {
  Ban,
  Copy,
  Eye,
  EyeOff,
  KeyRound,
  Loader2,
  PlayCircle,
  RefreshCw,
  Shield,
  Smartphone,
  UserPlus,
  XCircle,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api, ApiError } from "@/lib/api";
import type { ClientAccessCredentials } from "@/lib/api-types";

interface Props {
  clientId: string;
  clientEmail: string;
}

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PASSWORD_MIN = 8;

function passwordError(pw: string): string | null {
  if (!pw) return null; // empty = generated by the server
  if (pw.length < PASSWORD_MIN) return `Minimum ${PASSWORD_MIN} caractères`;
  if (!/[a-zA-Z]/.test(pw)) return "Au moins 1 lettre requise";
  if (!/[0-9]/.test(pw)) return "Au moins 1 chiffre requis";
  return null;
}

function errorMessage(e: unknown): string {
  if (e instanceof ApiError) return e.message;
  return e instanceof Error ? e.message : "Erreur inattendue";
}

export default function ClientAccessTab({ clientId, clientEmail }: Props) {
  const queryClient = useQueryClient();
  const queryKey = ["client-access", clientId];

  const accessQuery = useQuery({
    queryKey,
    queryFn: () => api.clientAccess.get(clientId),
  });

  const [createOpen, setCreateOpen] = useState(false);
  const [resetOpen, setResetOpen] = useState(false);
  const [revokeOpen, setRevokeOpen] = useState(false);
  const [credentials, setCredentials] = useState<ClientAccessCredentials | null>(null);

  const [email, setEmail] = useState(clientEmail);
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const refresh = () => {
    queryClient.invalidateQueries({ queryKey });
    queryClient.invalidateQueries({ queryKey: ["clients", clientId] });
  };

  const createMutation = useMutation({
    mutationFn: () =>
      api.clientAccess.create(clientId, { email: email.trim(), password: password || undefined }),
    onSuccess: (data) => {
      setCreateOpen(false);
      setCredentials(data);
      setPassword("");
      toast.success("Accès à l'application créé");
      refresh();
    },
    onError: (e) => setFormError(errorMessage(e)),
  });

  const resetMutation = useMutation({
    mutationFn: () => api.clientAccess.resetPassword(clientId, password || undefined),
    onSuccess: (data) => {
      setResetOpen(false);
      setCredentials(data);
      setPassword("");
      toast.success("Mot de passe réinitialisé — les sessions ouvertes sont fermées");
      refresh();
    },
    onError: (e) => setFormError(errorMessage(e)),
  });

  const suspendMutation = useMutation({
    mutationFn: () => api.clientAccess.suspend(clientId),
    onSuccess: () => {
      toast.success("Accès suspendu : le client est déconnecté");
      refresh();
    },
    onError: (e) => toast.error(errorMessage(e)),
  });

  const activateMutation = useMutation({
    mutationFn: () => api.clientAccess.activate(clientId),
    onSuccess: () => {
      toast.success("Accès réactivé");
      refresh();
    },
    onError: (e) => toast.error(errorMessage(e)),
  });

  const revokeMutation = useMutation({
    mutationFn: () => api.clientAccess.revoke(clientId),
    onSuccess: () => {
      setRevokeOpen(false);
      toast.success("Accès supprimé");
      refresh();
    },
    onError: (e) => toast.error(errorMessage(e)),
  });

  function openCreate() {
    setEmail(clientEmail);
    setPassword("");
    setFormError(null);
    setCreateOpen(true);
  }

  function openReset() {
    setPassword("");
    setFormError(null);
    setResetOpen(true);
  }

  function submitCreate() {
    if (!EMAIL_REGEX.test(email.trim())) return setFormError("Adresse email invalide");
    const pwErr = passwordError(password);
    if (pwErr) return setFormError(pwErr);
    setFormError(null);
    createMutation.mutate();
  }

  function submitReset() {
    const pwErr = passwordError(password);
    if (pwErr) return setFormError(pwErr);
    setFormError(null);
    resetMutation.mutate();
  }

  if (accessQuery.isLoading) {
    return (
      <Card>
        <CardContent className="py-12 flex justify-center">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </CardContent>
      </Card>
    );
  }

  if (accessQuery.isError) {
    return (
      <Card>
        <CardContent className="py-12 text-center space-y-3">
          <p className="text-sm text-destructive">{errorMessage(accessQuery.error)}</p>
          <Button variant="outline" size="sm" onClick={() => accessQuery.refetch()}>
            Réessayer
          </Button>
        </CardContent>
      </Card>
    );
  }

  const access = accessQuery.data!;
  const busy =
    suspendMutation.isPending || activateMutation.isPending || revokeMutation.isPending;

  return (
    <div className="space-y-4">
      {!access.has_access ? (
        <Card>
          <CardContent className="py-12 text-center">
            <Shield className="h-12 w-12 mx-auto text-muted-foreground/40 mb-4" />
            <p className="text-muted-foreground mb-1">Ce client n'a pas encore accès à l'application mobile</p>
            <p className="text-xs text-muted-foreground mb-6">
              Créez son compte : il pourra envoyer ses pièces, répondre à vos demandes et vous écrire.
            </p>
            <Button onClick={openCreate}>
              <UserPlus className="h-4 w-4 mr-2" />
              Créer l'accès client
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-sm font-medium flex items-center gap-2">
                <Smartphone className="h-4 w-4" />
                Compte application mobile
              </CardTitle>
              <Badge
                className={`text-xs border ${
                  access.is_active
                    ? "bg-emerald-100 text-emerald-800 border-emerald-200"
                    : "bg-amber-100 text-amber-800 border-amber-200"
                }`}
              >
                {access.is_active ? "Actif" : "Suspendu"}
              </Badge>
            </div>
          </CardHeader>
          <CardContent>
            <div className="grid sm:grid-cols-2 gap-y-3 gap-x-8 text-sm">
              <div>
                <span className="text-muted-foreground">Identifiant (email)</span>
                <p className="font-medium">{access.email}</p>
              </div>
              <div>
                <span className="text-muted-foreground">Créé le</span>
                <p className="font-medium">
                  {access.created_at ? new Date(access.created_at).toLocaleDateString("fr-FR") : "—"}
                </p>
              </div>
              <div>
                <span className="text-muted-foreground">Dernière connexion</span>
                <p className="font-medium">
                  {access.last_login ? new Date(access.last_login).toLocaleString("fr-FR") : "Jamais"}
                </p>
              </div>
            </div>

            <div className="flex flex-wrap gap-2 mt-6 pt-4 border-t border-border">
              <Button variant="outline" size="sm" onClick={openReset} disabled={busy}>
                <KeyRound className="h-3.5 w-3.5 mr-1.5" />
                Nouveau mot de passe
              </Button>
              {access.is_active ? (
                <Button variant="outline" size="sm" disabled={busy} onClick={() => suspendMutation.mutate()}>
                  <Ban className="h-3.5 w-3.5 mr-1.5" />
                  Suspendre
                </Button>
              ) : (
                <Button variant="outline" size="sm" disabled={busy} onClick={() => activateMutation.mutate()}>
                  <PlayCircle className="h-3.5 w-3.5 mr-1.5" />
                  Réactiver
                </Button>
              )}
              <Button
                variant="outline"
                size="sm"
                className="text-destructive hover:text-destructive"
                disabled={busy}
                onClick={() => setRevokeOpen(true)}
              >
                <XCircle className="h-3.5 w-3.5 mr-1.5" />
                Supprimer l'accès
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Create */}
      <Dialog open={createOpen} onOpenChange={(o) => !createMutation.isPending && setCreateOpen(o)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Créer l'accès client</DialogTitle>
            <DialogDescription>
              Le client se connectera à l'application mobile avec cet email et ce mot de passe.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <Label htmlFor="access-email">Email *</Label>
              <Input
                id="access-email"
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="client@exemple.fr"
              />
            </div>
            {renderPasswordField()}
            {formError && <p className="text-sm text-destructive">{formError}</p>}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateOpen(false)} disabled={createMutation.isPending}>
              Annuler
            </Button>
            <Button onClick={submitCreate} disabled={createMutation.isPending}>
              {createMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <UserPlus className="h-4 w-4 mr-2" />
              )}
              Créer le compte
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Reset password */}
      <Dialog open={resetOpen} onOpenChange={(o) => !resetMutation.isPending && setResetOpen(o)}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Nouveau mot de passe</DialogTitle>
            <DialogDescription>
              L'ancien mot de passe ne fonctionnera plus et le client sera déconnecté de ses appareils.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            {renderPasswordField()}
            {formError && <p className="text-sm text-destructive">{formError}</p>}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setResetOpen(false)} disabled={resetMutation.isPending}>
              Annuler
            </Button>
            <Button onClick={submitReset} disabled={resetMutation.isPending}>
              {resetMutation.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              Réinitialiser
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Revoke */}
      <AlertDialog open={revokeOpen} onOpenChange={setRevokeOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Supprimer l'accès du client ?</AlertDialogTitle>
            <AlertDialogDescription>
              Le client ne pourra plus se connecter. Ses documents et messages sont conservés. Vous pourrez
              recréer un accès plus tard.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={revokeMutation.isPending}>Annuler</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={(e) => {
                e.preventDefault();
                revokeMutation.mutate();
              }}
              disabled={revokeMutation.isPending}
            >
              Supprimer l'accès
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Credentials, shown once */}
      <Dialog open={credentials !== null} onOpenChange={(o) => !o && setCredentials(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Identifiants du client</DialogTitle>
            <DialogDescription>
              Transmettez-les au client. Le mot de passe ne pourra plus être affiché ensuite.
            </DialogDescription>
          </DialogHeader>
          {credentials && (
            <div className="space-y-3 py-2">
              <CopyRow label="Email" value={credentials.email} />
              <CopyRow label="Mot de passe" value={credentials.password} />
            </div>
          )}
          <DialogFooter>
            <Button onClick={() => setCredentials(null)}>J'ai noté les identifiants</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );

  function renderPasswordField() {
    return (
      <div className="space-y-2">
        <Label htmlFor="access-password">Mot de passe</Label>
        <div className="relative">
          <Input
            id="access-password"
            type={showPassword ? "text" : "password"}
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            placeholder="Laisser vide pour en générer un"
            className="pr-10"
            autoComplete="new-password"
          />
          <button
            type="button"
            className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
            onClick={() => setShowPassword((v) => !v)}
            aria-label={showPassword ? "Masquer" : "Afficher"}
          >
            {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
          </button>
        </div>
        <p className="text-xs text-muted-foreground flex items-center gap-1">
          <RefreshCw className="h-3 w-3" />
          Vide : un mot de passe solide est généré. Sinon 8 caractères minimum, lettres et chiffres.
        </p>
      </div>
    );
  }
}

function CopyRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between p-3 bg-muted rounded-lg">
      <div>
        <p className="text-xs text-muted-foreground">{label}</p>
        <p className="font-mono font-medium break-all">{value}</p>
      </div>
      <Button
        variant="ghost"
        size="icon"
        onClick={() => {
          navigator.clipboard.writeText(value).then(
            () => toast.success("Copié"),
            () => toast.error("Copie impossible"),
          );
        }}
      >
        <Copy className="h-4 w-4" />
      </Button>
    </div>
  );
}
